version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9-buster-node-browsers-legacy
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install pipenv
          command: |
            pip install --user pipenv
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Linting
          command: |
            isort .
            flake8 .
            black .
      - run:
          name: Run tests
          environment:
            TEST_DIR_OC_LETTINGS_SITE: "./oc_lettings_site/tests_oc_lettings_site/"
            TEST_DIR_LETTINGS: "./lettings/tests_lettings/"
            TEST_DIR_PROFILES: "./profiles/tests_profiles/"
          command: |
            cd ./oc_lettings_site/
            python -m manage test $TEST_DIR_OC_LETTINGS_SITE $TEST_DIR_LETTINGS $TEST_DIR_PROFILES
#      - run:
#          name: Docker Hub jobs
#          command: |
#            echo $docker_password | docker login --username $docker_username --password-stdin
#
#      - run:
#          name: Docker build
#          command: |
#            docker build -t p13_oc_lettings_site .
#      - run:
#          name: Run Docker container
#          command: |
#            docker run -d --name p13_oc_lettings_site_container p13_oc_lettings_site
      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Get Heroku API Key First Step
          command: |
            export HEROKU_API_KEY="$(heroku auth:token)"
      - run:
          name: Get Heroku API Key Second step
          command: |
            export HEROKU_API_KEY="$(heroku authorizations:info --json | jq -r '.access_token')"
      - run:
          name: Add Heroku API Key to CircleCI
          command: |
            echo "HEROKU_API_KEY=${HEROKU_API_KEY}" >> $BASH_ENV
      - run:
          name: Use Heroku API Key
          command: |
            echo $HEROKU_API_KEY | heroku auth:token
      - run:
          name: Create Heroku App
          command: |
            heroku create prodev-oc-lettings-site
      - run:
          name: Heroku Python Buildpack
          command: |
            heroku buildpacks:set heroku/python -a prodev-oc-lettings-site
      - run:
          name: Docker Auth Build and Push
          command: |
            echo $docker_password | docker login -u $docker_username --password-stdin
            docker build -t p13_oc_lettings_site .
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            docker tag p13_oc_lettings_site registry.heroku.com/prodev-oc-lettings-site/web
            docker push registry.heroku.com/prodev-oc-lettings-site/web:latest
      - run:
          name: Release to Heroku
          command: |
            heroku container:release web -a prodev-oc-lettings-site
