version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6

jobs:
  test_and_lint:
    executor: python/default
    steps:
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Test and Lint
          command: |
            isort .
            flake8 .
            black .
            cd ./oc_lettings_site/
            python -m manage test $TEST_DIR_OC_LETTINGS_SITE $TEST_DIR_LETTINGS $TEST_DIR_PROFILES

  deploy:
    executor: python/default
    steps:
      - run:
          name: Set Heroku API Key
          command: |
            echo "HEROKU_API_KEY=$HEROKU_API_KEY" >> $BASH_ENV
            echo $HEROKU_API_KEY | heroku auth:token
      - heroku/deploy-container:
          app_name: prodev-oc-lettings-site
          buildpack: heroku/python
          config_vars:
            PORT: $PORT
          container_registry:
            image: p13_oc_lettings_site
            username: $docker_username
            password: $HEROKU_API_KEY

workflows:
  test_and_deploy:
    jobs:
      - test_and_lint
      - deploy:
          requires:
            - test_and_lint
          filters:
            branches:
              only: developp
