version: 2.1

jobs:
  build:
    working_directory: ~/P13_Rondeau_Pierre
    docker:
      - image: circleci/python:3.9-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: |
            pip install --user pipenv
      - run:
          name: Install dependencies
          command: |
            pipenv install --ignore-pipfile
      - run:
          name: Run tests
          command: |
            pipenv run python manage.py test
