version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9-buster-node-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install pipenv
          command: |
            pip install --user pipenv
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          environment:
            TEST_DIR_OC_LETTINGS_SITE: "./oc_lettings_site/tests_oc_lettings_site/"
            TEST_DIR_LETTINGS: "./lettings/tests_lettings/"
            TEST_DIR_PROFILES: "./profiles/tests_profiles/"
          command: |
            python -m oc_lettings_site/manage test $TEST_DIR_OC_LETTINGS_SITE $TEST_DIR_LETTINGS $TEST_DIR_PROFILES