version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.2.0

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Linting and Testing
          command: |
            isort .
            flake8 .
            black .
            cd ./oc_lettings_site/
            python -m manage test $TEST_DIR_OC_LETTINGS_SITE $TEST_DIR_LETTINGS $TEST_DIR_PROFILES
      - run:
          name: Set the Heroku API Key
          command: |
            echo "HEROKU_API_KEY=$HEROKU_API_KEY" >> $BASH_ENV
            echo $HEROKU_API_KEY | heroku auth:token
      - heroku/deploy-container:
          app_name: prodev-oc-lettings-site
          image: p13_oc_lettings_site
          username: $docker_username
          password: $docker_password
      - run:
          name: Release the container
          command: heroku container:release web -a prodev-oc-lettings-site