version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.2.0

jobs:
  test_and_lint:
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Test and Lint
          command: |
            isort .
            flake8 .
            black .
            cd ./oc_lettings_site/
            python -m manage test $TEST_DIR_OC_LETTINGS_SITE $TEST_DIR_LETTINGS $TEST_DIR_PROFILES

  deploy:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: P13_Rondeau_Pierre/orb-p13_oc_lettings_site
      - run:
          name: Docker Login
          command: |
            echo "$PARAM_DOCKER_PASSWORD" | docker login -u "$PARAM_DOCKER_USERNAME" --password-stdin
      - docker/push:
          image: P13_Rondeau_Pierre/p13_oc_lettings_site
      - heroku/release-docker-image:
          api-key: HEROKU_API_KEY
          app-name: prodev-oc-lettings-site
          process-types: web

workflows:
  test_and_deploy:
    jobs:
      - test_and_lint
      - deploy:
          requires:
            - test_and_lint
          filters:
            branches:
              only: develop
