version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.2.0

jobs:
  test_and_lint:
    executor: python/default
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Test and Lint
          command: |
            isort .
            flake8 .
            black .
            cd ./oc_lettings_site/
            python -m manage test $TEST_DIR_OC_LETTINGS_SITE $TEST_DIR_LETTINGS $TEST_DIR_PROFILES

  heroku-build:
    executor: heroku/default
    steps:
      - run:
          name: Heroku API Key and App creation
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            export HEROKU_API_KEY="$(heroku auth:token)"
            echo "HEROKU_API_KEY=${HEROKU_API_KEY}" >> $BASH_ENV
            echo $HEROKU_API_KEY | heroku auth:token
            heroku create -a prodev-oc-lettings-site
            heroku buildpacks:set heroku/python -a prodev-oc-lettings-site

  release-heroku:
    executor: heroku/default
    steps:
      - run:
          name: Docker Auth, Build and Push to Heroku
          command: |
            echo $PARAM_DOCKER_PASSWORD | docker login -u $PARAM_DOCKER_PASSWORD --password-stdin
            docker build -t p13_oc_lettings_site .
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            docker tag p13_oc_lettings_site registry.heroku.com/prodev-oc-lettings-site/web
            docker push registry.heroku.com/prodev-oc-lettings-site/web:latest
            heroku container:release web -a prodev-oc-lettings-site

workflows:
  test_and_deploy:
    jobs:
      - test_and_lint
      - heroku-build:
          requires:
            - test_and_lint
          filters:
            branches:
              only: develop
      - release-heroku:
          requires:
            - heroku-build
          filters:
            branches:
              only: develop

