version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@2.0.0

jobs:
  test_and_lint:
    executor: python/default
    steps:
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            pip install -r ./requirements.txt
      - run:
          name: Test and Lint
          command: |
            isort .
            flake8 .
            black .
            cd ./oc_lettings_site/
            python -m manage test $TEST_DIR_OC_LETTINGS_SITE $TEST_DIR_LETTINGS $TEST_DIR_PROFILES

  deploy:
    executor: heroku/default
    steps:
      - run:
          name: Login to Heroku Docker image registry
          command: heroku container:login
      - run:
          name: Set Heroku API Key
          command: |
            echo "HEROKU_API_KEY=$HEROKU_API_KEY" >> $BASH_ENV
            echo $HEROKU_API_KEY | heroku auth:token
      - run:
          name: Deploy to Heroku
          command: |
            heroku container:push web -a prodev-oc-lettings-site
            heroku release -a prodev-oc-lettings-site



workflows:
  test_and_deploy:
    jobs:
      - test_and_lint
      - deploy:
          requires:
            - test_and_lint
          filters:
            branches:
              only: develop
