version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@2.0.0

jobs:
  test_and_lint:
    executor: python/default
    steps:
      - run:
          name: Install Dependencies
          command: |
            pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Test and Lint
          command: |
            isort .
            flake8 .
            black .
            cd ./oc_lettings_site/
            python -m manage test $TEST_DIR_OC_LETTINGS_SITE $TEST_DIR_LETTINGS $TEST_DIR_PROFILES

  deploy:
    executor: heroku/default
    steps:
      - heroku/install
      - run:
          name: Login to Heroku
          command: echo $HEROKU_API_KEY | heroku auth:login
      - heroku/push:
          api-key: $HEROKU_API_KEY
          app_name: prodev-oc-lettings-site
          recursive: false

workflows:
  test_and_deploy:
    jobs:
      - test_and_lint
      - deploy:
          requires:
            - test_and_lint
          filters:
            branches:
              only: develop
