# Generated by Django 3.2.16 on 2023-01-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Address"},
        ),
        migrations.AlterModelOptions(
            name="letting",
            options={"verbose_name": "Letting", "verbose_name_plural": "Lettings"},
        ),
    ]
